#!/usr/bin/env python3
import argparse
from pathlib import Path
from urllib.parse import urlparse

WORKER_JS = """export default {
  async email(message, env) {
    const rawEmail = await new Response(message.raw).text();
    const response = await fetch(env.WEBHOOK_URL, {
      method: \"POST\",
      headers: {
        \"Content-Type\": \"application/json\",
        \"Authorization\": \"Bearer \" + env.WEBHOOK_SECRET,
      },
      body: JSON.stringify({
        from: message.from,
        to: message.to,
        raw: rawEmail,
      }),
    });

    if (!response.ok) {
      message.setReject(`Webhook returned ${response.status}`);
    }
  },
};
"""


def build_readme(public_hostname: str, worker_name: str, webhook_url: str) -> str:
    return f"""# Cloudflare Email Worker bundle

Generated by `install-cloudflare-email-worker.sh`.

## Files

- `worker.js` — worker source
- `wrangler.toml` — Wrangler config
- `.dev.vars.example` — local dev environment example
- `CHECKLIST.md` — exact setup sequence for this deployment

## Deploy

```bash
wrangler login
wrangler deploy
printf '%s' '<secret>' | wrangler secret put WEBHOOK_SECRET
```

## This bundle is configured for

- Worker name: `{worker_name}`
- Stavrobot public hostname: `{public_hostname}`
- Webhook URL: `{webhook_url}`

## Notes

- This automates worker artifact generation and optional Wrangler deploy.
- Final Email Routing rule creation still happens in the Cloudflare dashboard.
"""


def build_checklist(public_hostname: str, worker_name: str, webhook_url: str, email_domain: str) -> str:
    return f"""# Cloudflare Email Routing checklist

## Values

- Worker name: `{worker_name}`
- Email Routing domain: `{email_domain}`
- Stavrobot public hostname: `{public_hostname}`
- Stavrobot inbound webhook URL: `{webhook_url}`

## Steps

1. Log into Cloudflare for the zone that handles `{email_domain}`.
2. Enable **Email Routing** for that zone if it is not already enabled.
3. From this directory, deploy the worker:

   ```bash
   wrangler deploy
   printf '%s' '<your webhook secret>' | wrangler secret put WEBHOOK_SECRET
   ```

4. In Cloudflare Email Routing, create or update a rule that sends inbound mail to worker `{worker_name}`.
5. Send a test message to an address on `{email_domain}`.
6. Confirm Stavrobot receives the webhook at `{webhook_url}`.
7. Add allowed sender addresses in Stavrobot `/settings` if needed.

## Validation hints

- `docker compose logs -f app` in the Stavrobot repo
- Worker logs in Cloudflare dashboard or `wrangler tail`
- Ensure `WEBHOOK_SECRET` exactly matches `[email].webhookSecret` in Stavrobot config
"""


def build_wrangler(worker_name: str, compatibility_date: str, account_id: str | None, webhook_url: str) -> str:
    lines = [
        f'name = "{worker_name}"',
        'main = "worker.js"',
        f'compatibility_date = "{compatibility_date}"',
    ]
    if account_id:
        lines.append(f'account_id = "{account_id}"')
    lines.extend([
        '',
        '[vars]',
        f'WEBHOOK_URL = "{webhook_url}"',
    ])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--public-hostname', required=True)
    parser.add_argument('--webhook-secret', required=True)
    parser.add_argument('--worker-name', required=True)
    parser.add_argument('--compatibility-date', required=True)
    parser.add_argument('--account-id')
    parser.add_argument('--out-dir', required=True)
    args = parser.parse_args()

    public_hostname = args.public_hostname.rstrip('/')
    parsed = urlparse(public_hostname)
    email_domain = parsed.hostname or '<your-domain>'
    webhook_url = f'{public_hostname}/email/webhook'
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / 'worker.js').write_text(WORKER_JS)
    (out_dir / 'wrangler.toml').write_text(
        build_wrangler(args.worker_name, args.compatibility_date, args.account_id, webhook_url)
    )
    (out_dir / '.dev.vars.example').write_text(
        f'WEBHOOK_URL={webhook_url}\nWEBHOOK_SECRET={args.webhook_secret}\n'
    )
    (out_dir / 'README.md').write_text(build_readme(public_hostname, args.worker_name, webhook_url))
    (out_dir / 'CHECKLIST.md').write_text(build_checklist(public_hostname, args.worker_name, webhook_url, email_domain))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
