#!/usr/bin/env python3
import argparse
from pathlib import Path

WORKER_JS = """export default {
  async email(message, env) {
    const rawEmail = await new Response(message.raw).text();
    const response = await fetch(env.WEBHOOK_URL, {
      method: \"POST\",
      headers: {
        \"Content-Type\": \"application/json\",
        \"Authorization\": \"Bearer \" + env.WEBHOOK_SECRET,
      },
      body: JSON.stringify({
        from: message.from,
        to: message.to,
        raw: rawEmail,
      }),
    });

    if (!response.ok) {
      message.setReject(`Webhook returned ${response.status}`);
    }
  },
};
"""

README = """# Cloudflare Email Worker bundle

Generated by `install-cloudflare-email-worker.sh`.

## Files

- `worker.js` — worker source
- `wrangler.toml` — Wrangler config
- `.dev.vars.example` — local dev environment example

## Deploy

```bash
wrangler login
wrangler deploy
printf '%s' '<secret>' | wrangler secret put WEBHOOK_SECRET
```

## Required Cloudflare setup

1. Enable Email Routing for your domain in Cloudflare.
2. Route inbound mail to this worker.
3. Ensure `WEBHOOK_URL` points to `https://<publicHostname>/email/webhook`.
4. Ensure `WEBHOOK_SECRET` matches Stavrobot `[email].webhookSecret`.

## Notes

- This only automates worker artifact generation and optional Wrangler deploy.
- Final Email Routing rule creation still happens in the Cloudflare dashboard.
"""


def build_wrangler(worker_name: str, compatibility_date: str, account_id: str | None, webhook_url: str) -> str:
    lines = [
        f'name = "{worker_name}"',
        'main = "worker.js"',
        f'compatibility_date = "{compatibility_date}"',
    ]
    if account_id:
        lines.append(f'account_id = "{account_id}"')
    lines.extend([
        '',
        '[vars]',
        f'WEBHOOK_URL = "{webhook_url}"',
    ])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--public-hostname', required=True)
    parser.add_argument('--webhook-secret', required=True)
    parser.add_argument('--worker-name', required=True)
    parser.add_argument('--compatibility-date', required=True)
    parser.add_argument('--account-id')
    parser.add_argument('--out-dir', required=True)
    args = parser.parse_args()

    public_hostname = args.public_hostname.rstrip('/')
    webhook_url = f'{public_hostname}/email/webhook'
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / 'worker.js').write_text(WORKER_JS)
    (out_dir / 'wrangler.toml').write_text(
        build_wrangler(args.worker_name, args.compatibility_date, args.account_id, webhook_url)
    )
    (out_dir / '.dev.vars.example').write_text(
        f'WEBHOOK_URL={webhook_url}\nWEBHOOK_SECRET={args.webhook_secret}\n'
    )
    (out_dir / 'README.md').write_text(README)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
